export type Tag =
  | 'love'
  | 'cheating'
  | 'confession'
  | 'heartbreak'
  | 'romance'
  | 'fairytale'
  | 'satire'
  | 'media'
  | 'self-empowerment'
  | 'positivity'
  | 'dance'
  | 'unrequited'
  | 'yearning'
  | 'waiting'
  | 'idealization'
  | 'delusion'
  | 'betrayal'
  | 'revenge'
  | 'forgiveness'
  | 'growth'
  | 'reflection'
  | 'regret'
  | 'nostalgia'
  | 'what ifs'
  | 'youth'
  | 'longing';
